### ISSUE TITLE
有没有朋友能教一下怎么跑通这个程序啊？

### ISSUE THREAD

**Issue by Xinxin1119** [mouna99/dien#46]
我在pycharm跑train.py的时候出现错误
Traceback (most recent call last):
  File "E:/CTR/dien-master/script/train.py", line 233, in <module>
    if sys.argv[1] == 'train':
IndexError: list index out of range

然后在命令行输入python train.py train DIEN也有错误
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    train(model_type=sys.argv[2], seed=SEED)
  File "train.py", line 145, in train
    model = Model_DIN_V2_Gru_Vec_attGru_Neg(n_uid, n_mid, n_cat, EMBEDDING_DIM, HIDDEN_SIZE, ATTENTION_SIZE)
  File "e:\CTR\dien-master\script\model.py", line 387, in __init__
    self.build_fcn_net(inp, use_dice=True)
  File "e:\CTR\dien-master\script\model.py", line 102, in build_fcn_net
    self.optimizer = tf.train.AdamOptimizer(learning_rate=self.lr).minimize(self.loss)
AttributeError: 'Model_DIN_V2_Gru_Vec_attGru_Neg' object has no attribute 'lr'

**Comment by Wkdwlaud** [comment]
感觉是tf版本问题？用的是tensorflow==1.4.0吗？

**Comment by WinnieZM** [comment]
我也是这个问题，下的版本也是TensorFlow==1.4.0
